services:
  testproject:
    image: ${DOCKER_REGISTRY-}testproject
    build:
      context: .
      dockerfile: TestProject/Dockerfile

  testconsumer:
    image: ${DOCKER_REGISTRY-}testconsumer
    build:
      context: ..
      dockerfile: TestConsumer/Dockerfile

  rabbit:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 30s
      retries: 5
